version: "3"

services:
  news-pay-per-api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 8080:8080
    networks:
      - newspayperNetwork
networks:
  newspayperNetwork: