version: "3"

services:
  mysql:
    image: mysql:8.0.21
    restart: always
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "NewsPayPer"
    ports:
      - 3306:3306
    networks:
      - newspayperNetwork

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 8080:8080
    networks:
      - newspayperNetwork
volumes:
  db:
networks:
  newspayperNetwork:
